### ISSUE TITLE
travis::travis_enable() error

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/travis#102]
While testing a new fake repo, I constantly get this. Already authenticated repos work fine, i.e. when using `travis::travis_browse()`.

```r
Error in `_f`(gh_token = gh_token) : 
  Unprocessable Entity (WebDAV; RFC 4918) (HTTP 422). Failed to authenticate with travis.
```

GH PAT should be fine.

**Comment by krlmlr** [comment]
Can you create the repo manually on https://travis-ci.org?

**Comment by pat-s** [comment]
Yes.

**Comment by pat-s** [comment]
Works in master. So probably an error on my side. Investigating..
