### ISSUE TITLE
Unauthorized (HTTP 401)

### ISSUE THREAD

**Issue by annahutch** [ropenscilabs/travis#104]
Installation of package seems fine on macOS but calling the functions does not open the browser windows required to authorise the app (localhost 1410 error). @kkmann

Also get this error in R:
```> github_repo()
  Error in get_repo_data(repo, gh_token = gh_token) : 
  Unauthorized (HTTP 401). Failed to retrieve repo information for: annahutch/corrcoverage.```

**Comment by kkmann** [comment]
Hey, thx btw for the amazing package - did realize how complicated this stuff is until we ran into said problem with the travis package ;) 

We also tried to set up everything manually, but the docs for the entire process are a bit sparse for non CI experts. It would be extremely handy to have a more extensive documentation what the travis package actually does under the hood (both in terms of fallback and just to understand this stuff more thoroughly)

**Comment by krlmlr** [comment]
Can you please post the full console output? Can you please try `tic::use_tic()` ?

**Comment by kkmann** [comment]
btw, `travis::enable_travis(); travis::use_travis_deploy()` works fine for me under Ubuntu 19.04.

**Comment by kkmann** [comment]
okay, embarrassingly it was just the missing httpuv package, sorry!

I would still be super grateful for a more extensive manual walkthrough in case you find the time at some point ;)

**Comment by pat-s** [comment]
Hm, _httpuv_ should not be a requirement here? Are you really sure that this was the problem? Can you recreate the problem when removing _httpuv_ again?

**Comment by annahutch** [comment]
Yes, when uninstalling the _httpuv_ the problem returns.

**Comment by kkmann** [comment]
Well, on a vanilla install of R on macOS without httpuv, calling `enable_travis()` literally complains about the package httpuv not being installed. removing it again, recreates the problem.

**Comment by annahutch** [comment]
```
> remove.packages("httpuv")
> travis_enable()
❯  Authenticating to GitHub.
httpuv not installed, defaulting to out-of-band authentication
```

and a webpage opens with 
![image](https://user-images.githubusercontent.com/42926930/60709161-b6aeb080-9f07-11e9-9e4b-f7828f895aab.png)

When I then install _httpuv_ everything works fine. I installed travis using 
```
remotes::install_github("ropenscilabs/travis")
```
btw :)

**Comment by pat-s** [comment]
Thanks, this information helps!

**Comment by pat-s** [comment]
After merging #115 we now use a new authentication scheme which should hopefully have cleared this issue.
Please report back if you still face issues.
