### ISSUE TITLE
Scheduling longer build times

### ISSUE THREAD

**Issue by cimentadaj** [ropenscilabs/travis#106]
Is there currently a way from `travis` (R package) to allow for longer build times (> 10ms)? I know there are ways in travis ([here](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)) so maybe there's a way to implement it here.

**Comment by pat-s** [comment]
Thanks for asking. This is currently not possible.

**Comment by pat-s** [comment]
And not possible anyhow via the API.
