### ISSUE TITLE
Error: callr subprocess failed: '*' is non-empty and not built by pkgdown

### ISSUE THREAD

**Issue by MarkEdmondson1234** [ropenscilabs/travis#107]
I authenticated fine with GitHub etc. using `travis::use_travis_deploy()` from an install today.

But I get this error when it tries to build the website:

```

══ Building pkgdown site ═══════════════════════════════════════════════════════

Reading from: '/home/travis/build/MarkEdmondson1234/googleAuthR'

Writing to:   '/tmp/Rtmp1k9COG/file331444f9d92f'

Error : '/tmp/Rtmp1k9COG/file331444f9d92f' is non-empty and not built by pkgdown

Error: callr subprocess failed: '/tmp/Rtmp1k9COG/file331444f9d92f' is non-empty and not built by pkgdown

Execution halted

Script failed with status 1
```

See [this build](https://travis-ci.org/MarkEdmondson1234/googleAuthR/builds/579011568) for the full logs.

**Comment by pat-s** [comment]
Hi,

this looks unrelated to _travis_ and more likely to be caused by _pkgdown_. Can you built the site locally using `pkgdown::build_site()`?

**Comment by MarkEdmondson1234** [comment]
Yes I've been building a website to date by doing it locally then uploading - does that mean I need to delete some local files first before submitting to GitHub for travis to build it?

**Comment by pat-s** [comment]
I haven't seen this particular error msg before. I would give it a try with `build_site(new_process = FALSE)` and `build_site(document = FALSE)`. 

Insert the argument into `do_pkgdown()` in `tic.R`.

**Comment by MarkEdmondson1234** [comment]
I think it may be because my website is built from the master branch `/docs` folder, and not a `gh-pages` branch.  I've removed it for now.

**Comment by pat-s** [comment]
> I think it may be because my website is built from the master branch /docs folder, and not a gh-pages branch. I've removed it for now.

Travis/pkgdown does not care where your website is built. _pkgdown_ always builds to `docs/`.

I just see that you are not using _tic_ + _travis_ but only _travis_.
The _travis_ package is not responsible for anything that happens in your _pkgdown_ build. And it also does not push the code for you.

You can try https://pkgdown.r-lib.org/reference/deploy_site_github.html or https://github.com/ropenscilabs/tic.package for _pkgdown_ automation.

**Comment by muschellij2** [comment]
FYI - I ran into this and it was due to a newer version of `pkgdown` running on Travis vs. the one used to generate the `pkgdown` site locally.  The older version did not make `docs/pkgdown.yml`, which the new `pkgdown` requires (or will fail with error above).  Just FYI for those who find themselves here.

**Comment by vbonhomme** [comment]
+ for some reason, badly formatted "reference" section in `_pkdown.yml` can also trouble the game
