### ISSUE TITLE
Simplify Travis authentication

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/travis#109]
I have a working prototype in the `gh` branch that only reduces the querying for the Travis PAT (which is the main function opening all the browser windows).

Also caching the token seems to work for now. Even though this needs more tests. Why should the token not be cached and needs to be always fresh as mentioned in a comment in the code?

In addition I updated the console messages to make them more descriptive and accurate.

```r
travis_repo_info()
retrieve repo information for: 'ropenscilabs/travis'
❯ Querying your Travis CI Personal Access Token.
❯ Authenticating to GitHub to log into Travis with your GH account.
✔ Authentication successful.
Repository ropenscilabs/travis: Set Up Travis for Testing and Deployment


# here with cached token
> travis_repo_info()
retrieve repo information for: 'ropenscilabs/travis'
Repository ropenscilabs/travis: Set Up Travis for Testing and Deployment
```

**Comment by krlmlr** [comment]
Caching GitHub tokens hasn't worked for a long time, now it seems to work (at least on travis-ci.com .) This should reduce the number of auth requests. 

Independently, we can make sure that `use_tic()` grabs a token with the necessary scopes up front and uses it, to further reduce the number of requests.

**Comment by pat-s** [comment]
done in #115
