### ISSUE TITLE
Auth: Consider using Travis API token instead of Github OAuth2.0

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/travis#111]
This might simplify auth processes for users. Also I guess it is the "official" way suggested by Travis.

I also use this way in the circle api pkg I am creating right now and it seems to work fine (token is stored on disk and needs to be created only once). 

Is there any advantage I am overlooking for using Github based OAuth2.0?

**Comment by krlmlr** [comment]
Direct auth seems clearly better if it works. Originally, users had to auth to GitHub first before they could auth with Travis.

**Comment by pat-s** [comment]
Ok. Thanks for the quick reply, I'll refactor the auth process then.

**Comment by pat-s** [comment]
Done in #115
