### ISSUE TITLE
extract_repo is unable to handle 'www' in repository urls

### ISSUE THREAD

**Issue by thebioengineer** [ropenscilabs/travis#114]
Hi All, I was trying to use {travis} and came across an this issue. I looked at the underlying function, and it looked like there was some functionality to escape the 'www', but appeared not to be working. I also did not see the tests using 'www' in their URLs. 

Below is a reprex:
``` r
travis:::extract_repo("https://www.github.com/thebioengineer/tidytuesdayR.git")
#> Error: Unrecognized repo format: https://www.github.com/thebioengineer/tidytuesdayR.git
```

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Thanks, we'll add it to the list :)
