### ISSUE TITLE
use_travis_deploy in travis-com branch

### ISSUE THREAD

**Issue by Athanasiamo** [ropenscilabs/travis#116]
Hey.

Trying to get some repos working with .com. I've installed the `travis-com` branch, but when I try to run `use_travis_deploy`, the Travis CI API token part fails as I am routed to a page I dont seem to have access to? [https://travis-ciask/account/preferences](https://travis-ciask/account/preferences), and the R console is waiting for me to paste a token, which I obv cant access without this page.

**Comment by pat-s** [comment]
Thanks for testing! That's odd though.

Routing works for me, the url should be: https://travis-ci.com/account/preferences
Even when being signed out you should be redirected to the login page.

How exactly does your call to `use_travis_deploy()` look like?

**Comment by Athanasiamo** [comment]
I found the culprit.

I start off like so 

```
> library(travis)
Env var 'R_TRAVIS' not set. Defaulting to '.org' endpoint.
```

fair enough, I have not specified my endpoint yet, org is a decent default. 

However, it does not seem like `use_travis_deploy` is picking it up. 
when I supply `endpoint = ".com"`  or `endpoint = ".org"` it works just fine.

**Comment by pat-s** [comment]
Thanks! That helped me. Can you try installing the latest rev of the branch and see if it works now? Optimally by temporarily reverting your recently set env vars (if so).

**Comment by Athanasiamo** [comment]
Thanks for the quick fix! I'm in meetings the remainder of the day, but will get to it tomorrow morning. I'll let you know how I fare!

**Comment by Athanasiamo** [comment]
Got to this now, but am now getting 

```
> use_travis_deploy(endpoint = ".com")
❯ Adding deploy keys on GitHub and Travis CI for repo 'ggseg'.
───────────────────────────────────────────────────────────────────────────────────────────
✔ Added a public deploy key to GitHub for repo 'ggseg'.
Error: 
```
Very unsure what's happening there. Also happens with ".org". Maybe github is mad at me deploying a million keys today trying to figure this out. I'll check again tomorrow

**Comment by pat-s** [comment]
Thanks for alpha testing. I'll check tmrw again as well. Unfortunately we have no tests here yet (because it's not so trivial with all the repeated requests). Let's see if I can come up with a solution.

**Comment by Athanasiamo** [comment]
I still get the same error, but if there is a github block (and I suspect it is) I might need to wait for 24 since the last try or something. I'll let it lie over the weekend. I'll also contact github support, they might be able to confirm this hypothesis.

**Comment by Athanasiamo** [comment]
On inspection, the key _is_ being added to github, so it is failing a step right after that? 
I'm guessing it is this part that is failing, so it's a travis thing. 

```
   travis_set_var("id_rsa", private_key, public = FALSE, repo = github_repo(), 
        endpoint = endpoint)
```

**Comment by pat-s** [comment]
Great! That saves me a lot time. I will clear that later. Thanks for all the help!

**Comment by pat-s** [comment]
I've just pushed some commits to the branch.

- Existing env vars on Travis and existing deploy keys (added by pkg travis) are now deleted automatically (to avoid conflicts like above and to clean up)
- Deploy key name now has the endpoint in the title (good point!)

**Comment by pat-s** [comment]
@Athanasiamo Is this issue solved for you? then we can close here.

**Comment by Athanasiamo** [comment]
Hi! Sorry for not replying and closing the issue, I really thought I did. yes, this resolved it for me. Thanks a bunch for such quick response.
