### ISSUE TITLE
Get repo slug from DESC$URL instead of the git repo info

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/travis#117]
Because the latter is not available in tests.
Nowadays it is a quasi standard to have a URL field in the DESC file containing the Github repo slug.

**Comment by krlmlr** [comment]
Why is it important to have it in tests?

**Comment by pat-s** [comment]
With the repo slug I can get all the information about the repo I need using the {gh} pkg. Currently the slug is retrieved from the repos git config.
I want to create a test repo since I do not want to test funs like `use_travis_deploy()` on the main repo.

Am I missing something?

**Comment by krlmlr** [comment]
Can we do

```sh
git init testrepo
cd testrepo
git remote add testrepo origin https://github.com/owner/testrepo
```

so that the tests pick it up?

I'm wary about functional changes to accommodate tests, if this is the only reason for the change. Less freedom to change things later on.

**Comment by pat-s** [comment]
This could also do the trick. I can try doing this in `tests/testthat/helpers_git.R` via `git2r`.

I thought using the DESCRIPTION entry would be more canonical but this is debatable and since it would also come with a change...

**Comment by pat-s** [comment]
Works, see #118. Thanks!
