### ISSUE TITLE
Think how to deal with hidden {{tic}} dependency

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/travis#120]
https://github.com/ropenscilabs/travis/pull/115#discussion_r357943501

_tic_ checks for an env var named `id_rsa` in `tic::ci_can_push()` which requires Travis setting up an env var with this name to work correctly.
This builds a hidden dependency on the {{tic}} package. 
How can we resolve this?

**Comment by krlmlr** [comment]
Host the relevant logic in {tic}?

**Comment by pat-s** [comment]
Hm, tricky. In {circle} users can use `use_circle_deploy()` universally without having to install the key first. This is done in the background by Circle CI.

With `use_travis_deploy()` one needs to "install" the SSH key pair and hence the function is only usable in conjunction with {tic} at the moment.

However, the main problem is that the naming of the SSH key pair is not exposed. This would uncouple both packages in terms of hidden deps?

# Proposal

- Give the user the ability to name the SSH key pair differently (both private and public key)
- Name the default for the private key used by {tic} not `id_rsa` but something like `travis-tic-deploy-key` (added bonus for clarity)

This way, we can call `use_travis_deploy(name_private = XY, name_public = XX)` in {tic} and have no hidden dependency anymore because it is clear what we require. We can check for that specific name in `ci_can_push()` and issue a warning if missing which indicates that the user should call `travis::use_travis_deploy(name_private = XY, name_public = XX)` to enable deployment.

In `use_travis_deploy()` we stop early anyway if the public key exists. If not (because the user might have deleted it), we also delete a potential existing private key because a new public key would give a mismatch with the existing old private key.

In fact, we should do the same to the public key because the user could also go the other way round and just delete the env var stored on Travis with the public key still being in the repo.


-> We should check for the existence of both and if 1 out of 2 is missing, we delete the respective other.

**Comment by krlmlr** [comment]
`name_private` and `name_public` sounds good, with a default -- there's other machinery that already relies on `travis::use_travis_deploy()`.

Regarding stale keys: perhaps we should delete both, GitHub first, then Travis, before attempting to create new keys.
