### ISSUE TITLE
Implement own browse_travis()

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#121]
again. Don't reexport from {usethis}, because the latter doesn't know about `.com` .

**Comment by pat-s** [comment]
Maybe there is a midunderstanding? `usethis::browse_travis()` knows about `.com`:

```
browse_travis(package = NULL, ext = c("org", "com"))
```

It just does not respect the env vars used by {travis}.

**Comment by krlmlr** [comment]
Should we roll our own `browse_travis()` that "just works"?

**Comment by pat-s** [comment]
We could, but I see also possibly redundant (maintenance) work and possible confusion on the user side.

Another option would be to adapt the {usethis} model by changing arg `endpoint` to `ext` and `.org` to `org` and `.com` to `com`?
