### ISSUE TITLE
Running Travis deploy using the ".org" endpoint

### ISSUE THREAD

**Issue by nuno-agostinho** [ropenscilabs/travis#135]
While trying to run `travis::use_travis_deploy(endpoint=".org")` with the `R_TRAVIS_ORG` variable set in the `.Renviron` file, I keep getting the following error:

```
x To interact with the Travis CI API, an API token is required. Please call
  `browse_travis_token()` first. Alternatively, set the API key via env vars `R_TRAVIS_ORG`
  or `R_TRAVIS_COM`.
Error: Travis API key missing.
```

This may be related with line 43 of **setup.R** where `travis_check_api_key()` is called without indicating the endpoint of interest. After manually editing this line to `travis_check_api_key(endpoint)`, the function continued running without any issue.

https://github.com/ropenscilabs/travis/blob/b8197c4f67115e3de084c352784a820de8cb56e6/R/setup.R#L29-L43

**Comment by pat-s** [comment]
The default endpoint is `.com`. If you set `R_TRAVIS_ORG` and the endpoint is `.com`, you have no valid API key.

You also need to set `R_TRAVIS = ".org"` to make it work.

Maybe we should add an assertion for this special case and write out a custom error message.

**Comment by nuno-agostinho** [comment]
> The default endpoint is `.com`. If you set `R_TRAVIS_ORG` and the endpoint is `.com`, you have no valid API key.

I understand that behaviour by default. However, if I'm explicitly calling `travis::use_travis_deploy(endpoint=".org")`, it should check for the `R_TRAVIS_ORG` API key. As per the the definition of the `endpoint` argument when running `?use_travis_deploy`, you don't need to set `R_TRAVIS`:

> endpoint: [string] Which Travis endpoint to use. Defaults to ".org". Accepted values are ".com" and ".org". Can be set globally via env var `R_TRAVIS`.

Otherwise, what is the point of the `endpoint` argument?

**Comment by pat-s** [comment]
> Update: Just noticed that the endpoint should be ".org" by default according to the argument definition... shouldn't it be written that it is ".com" by default?

Yes, that's wrong. Needs to be updated. Thanks!

> I understand that behaviour by default. However, if I'm explicitly calling travis::use_travis_deploy(endpoint=".org"), it should check for the R_TRAVIS_ORG API key. 

Yes, that should work. We even have tests for this so I'm wondering what might go wrong here.
I overlooked that you were setting the endpoint explicitly in your first post, sorry.

So to verify: 

- You have set `R_TRAVIS_ORG` 
- were calling any travis function with `endpoint = ".org"` and were getting the error from above?

I'll try to have a look in the evening.

**Comment by nuno-agostinho** [comment]
> * You have set `R_TRAVIS_ORG`
> * were calling any travis function with `endpoint = ".org"` and were getting the error from above?

Yup, exactly that! :)

**Comment by pat-s** [comment]
Thanks for reporting. Both of your issues were correct and the `endpoint` arg was indeed missing in `use_travis_deploy()`.

Should work now. If not, please report back :)
