### ISSUE TITLE
Redirect https://ropenscilabs.github.io/travis/ to new site

### ISSUE THREAD

**Issue by peterdesmet** [ropenscilabs/travis#139]
On https://pkgdown.r-lib.org/reference/deploy_site_github.html I noticed a link to the documentation website of this package, but https://ropenscilabs.github.io/travis/ now returns a 404, since the website lives at https://docs.ropensci.org/travis/

Rather than updating the link at pkgdown, it might be good to redirect all old links `openscilabs.github.io/x` to `docs.ropensci.org/x`. We've done that for INBO with a separate repo: https://github.com/inbo/inbo.github.io

ping @sckott

**Comment by sckott** [comment]
thanks @peterdesmet 

@pat-s I think we were doing a redirect here https://github.com/ropenscilabs/ropenscilabs.github.io/blob/master/404.html - should I add travis and tic ?

**Comment by pat-s** [comment]
@sckott Sure, if that helps :)

**Comment by sckott** [comment]
thanks 

@peterdesmet i'm not sure we want to redirect any `ropenscilabs.github.io/` link to `docs.ropensci.org/` as not all repos will have a `docs.ropensci.org/` page

**Comment by peterdesmet** [comment]
@sckott yeah, that makes sense. I mostly wanted the travis link fixed.

**Comment by sckott** [comment]
@peterdesmet should be fixed now
