### ISSUE TITLE
Default of travis does not match the pkgdown

### ISSUE THREAD

**Issue by llrs** [ropenscilabs/travis#142]
`pkgdown::deploy_site_github` expects the deploy key to be named as `id_rsa`

However, travis::use_travis_deploy` creates an environment variable `TRAVIS_DEPLOY_KEY`. 

Perhaps the default of both packages could agree, I think the easier is to change to be `use_travis_deploy(key_name_private = "id_rsa")` the default, at least this could be mentioned in the example or in the vignette (it took me 2 days to understand why a build was failing :(

**Comment by pat-s** [comment]
{travis} have no relation to {pkgdown} and I do not have influence on what {pkgdown} does.

`id_rsa` is the old default and still supported. Where are you running into problems? Open a separate issue for this please if you still encounter problems.

In the future we will probably switch to `TIC_DEPLOY_KEY` for all R-CI client packages hosted under the ropensci umbrella.

**Comment by llrs** [comment]
I know that {travis} and {pkgdown} are not related, but since one recommends the other I thought that it would be better for your users to have it sensible defaults. 

As a user {pkgdown} uses id_rsa and recommends using `use_travis_deploy`, however as {travis} has moved away from id_rsa I didn't understand why Travis failed to deploy the site despite following its advice. 
I found the way to create the enviroment id_rsa as I posted in the first message, so no, I do not longer have this problem. 

Thank you very much for maintaining and developing this package. I wouldn't deploy or use Travis if it wasn't by this package.

**Comment by pat-s** [comment]
> As a user {pkgdown} uses id_rsa and recommends using use_travis_deploy

{pkgdown} just did not update to the newest change. The tidyverse is moving all efforts to GitHub Actions anyway so its not surprising that no time has been put into this yet.

> however as {travis} has moved away from id_rsa I didn't understand why Travis failed to deploy the site despite following its advice.

As said, `id_rsa` is still supported. Idk what you did in detail but `travis::use_travis_deploy(key_name_private = "id_rsa")` should work.

> Thank you very much for maintaining and developing this package. I wouldn't deploy or use Travis if it wasn't by this package.

Thanks! It is not perfect but certainly helps. I just do not have enough time to robustify it more right now (i.e. adding a more sophisticated test suite than the current one).
