### ISSUE TITLE
use_travis_deploy() fails with GitHub API error (404)

### ISSUE THREAD

**Issue by MLopez-Ibanez** [ropenscilabs/travis#144]
I followed the instructions here:

https://docs.ropensci.org/travis/articles/travis.html

and I get:
```
> travis::use_travis_deploy()
ℹ Querying Github deploy keys from repo.
Error in gh_process_response(raw) : 
GitHub API error (404): 404 Not Found
Message: Not Found
Read more at https://developer.github.com/v3/repos/keys/#list-deploy-keys

URL not found: https://api.github.com/repos/MLopez-Ibanez/irace/keys
```

**Comment by MLopez-Ibanez** [comment]
Also, there is some step missing. I had to manually add the GITHUB_PAT token to Travis settings.

**Comment by pat-s** [comment]
`use_travis_deploy()` now errors instead of just throwing a warning. I also added an additional sentence to the "Getting Started" vignette to reflect the requirement.
