### ISSUE TITLE
URL typo for .org

### ISSUE THREAD

**Issue by camille-s** [ropenscilabs/travis#145]
Calling  `travis::browse_travis_token(endpoint = "org")` gets a browser error, because the URL it's routed to is missing the "." in ".org". Shown in the printout for "Opening URL":

```
> travis::browse_travis_token("org")
ℹ Querying API token...
→ Opening URL <https://travis-ciorg/account/preferences>.
ℹ Call `usethis::edit_r_environ()` to open ~/.Renviron and store the API key as
  env var `R_TRAVIS_COM` (or `R_TRAVIS_ORG` if you are using the '.org'
  endpoint). Example: `R_TRAVIS_COM = <key>`

The API key can alternatively be stored in ~/.travis/config.yml. This is only
  suggested if you previously used the Travis CI CLI tool.
```

~~The dot-com version works as expected.~~ Actually nevermind, the "com" version has the same issue with `travis::browse_travis_token(endpoint = "com")`.

**Comment by pat-s** [comment]
This is not an issue. Only ".com" and ".org" are valid options, see `?browse_travis_token`.

**Comment by camille-s** [comment]
Sorry, I missed the "." in what had to be in the endpoint
