### ISSUE TITLE
Github permission issue

### ISSUE THREAD

**Issue by jeroenooms** [ropenscilabs/travis#28]
I noticed that deploying a new key to github fails with 404 for all my repositories in ropensci. It works for all my repositories under my own name. This is probably a security limitation on github because I am not admin in `ropensci` although I do have admin access to those repositories.

**Comment by karthik** [comment]
Want me to try since I have owner access?

**Comment by jeroenooms** [comment]
Could you try if `use_travis_vignettes()` works for repos you have in the `ropensci` or other orgs?

**Comment by jeroenooms** [comment]
Hmm I'm getting the same problem for my repos in `rstats-db` where I am owner. Really strange. It shouldn't be a permission issue because I can manually add deploy keys through the web gui.

**Comment by jeroenooms** [comment]
I'm going to ask GH support about this.

**Comment by karthik** [comment]
ok.

**Comment by jeroenooms** [comment]
Here is the response from GH support:

> Yep, it's a security feature, Jeroen. The token you're using was created for an OAuth application called "rtravis". And the organization you're targeting has this feature enabled:

> https://help.github.com/articles/about-third-party-application-restrictions/

> However, the "rtravis" application hasn't been whitelisted by the organization. As a result, requests made with tokens for that application are treated as being made by a non-member.

> Try whitelisting that application or disabling the feature and let me know if that doesn't help.

**Comment by krlmlr** [comment]
The current release tries its best to direct the user to click the right buttons. Please let me know if it works for you.
