### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#50]
- [x] functions
- [x] pkgdown index
- [x] relation to tic
- [ ] _remake_ tests

Here, moving most of the README to a "Get started" vignette and adding more focused vignettes seems useful too.

From https://github.com/ropenscilabs/travis/pull/92#issue-232801290:

- [ ] Clean up README to avoid redundancy
- [ ] Split into subsections, e.g. for `travis_get_logs()`
- [ ] Think about separate subsection regarding the relation to tic and usethis.
- [x] What happens when the user uses the package for the first time?
    - [x] rtravis app
    - [ ] Screenshots
    - [x] Multiple authentications
- [x] Describe prerequisites, in a similar way to tic
- [ ] Double-check usage of `use_tic()`

**Comment by karthik** [comment]
I can take this on

**Comment by pat-s** [comment]
outdated
