### ISSUE TITLE
Use gh

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#54]
for accessing GitHub API.

https://github.com/r-pkgs/gh

Probably depends on CRAN availability of gh. @gaborcsardi: Any plans?

**Comment by gaborcsardi** [comment]
Yeah, working on writing some tests for it and then it is good to go.

**Comment by krlmlr** [comment]
@gaborcsardi: Any news regarding CRAN release of gh?

**Comment by gaborcsardi** [comment]
I have no good way to test it, and I am a bit uncomfortable with publishing it without tests.

**Comment by krlmlr** [comment]
Thanks for the heads-up. It looks difficult to test such a package, but perhaps you could restrict the tests to those parts of the behavior that you can control, and then gradually expand.

**Comment by krlmlr** [comment]
We'll do it manually for now, especially because basic auth seems out of scope for the gh package.

**Comment by krlmlr** [comment]
Don't care about basic auth anymore, but the issue is moot while gh is not on CRAN.

CC @karthik.

**Comment by gaborcsardi** [comment]
OK. I changed my mind, and I can put it on CRAN without the proper tests.

**Comment by krlmlr** [comment]
Mocking the entire GitHub API seems too much asked for. We could still test those parts of the package that we can control.

**Comment by pat-s** [comment]
Done in #115
