### ISSUE TITLE
Have this repo or cloudyr/travissci listed on Travis website

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/travis#65]
https://docs.travis-ci.com/api/#api-clients

cc @leeper

**Comment by karthik** [comment]
ok

**Comment by leeper** [comment]
I'm submitting a PR with some code additions that reflect features available over in [cloudyr/travis](https://github.com/cloudyr/travisci) but not available here. I'll archive that project with a redirect notice to here.

Features available over there (ticked things I've merged into this code):

- [x] restart the last build
- [ ] get branches
- [x] get/delete logs
- [x] get/delete caches
- [ ] [linting for `.travis.yml` files](https://developer.travis-ci.com/resource/lint#Lint)
- [x] get [repo settings](https://developer.travis-ci.com/resource/settings#Settings)
- [ ] set repo settings
- [x] S3 classes for some of the objects w/ print methods

I think that's all the relevant functionality. Not sure how important the unticked things are?

**Comment by krlmlr** [comment]
Added PR to list it on https://docs.travis-ci.com/user/apps/#libraries.

**Comment by krlmlr** [comment]
Upstream PR was merged.
