### ISSUE TITLE
Link to basic intro to travis

### ISSUE THREAD

**Issue by karthik** [ropenscilabs/travis#66]
- What is travis, why use CI
- Benefits of using CI
- Maybe link to a screencast on how this workflow goes (but more important for tic than here)

**Comment by krlmlr** [comment]
Perhaps http://mahugh.com/2016/09/02/travis-ci-for-test-automation/.

**Comment by pat-s** [comment]
Do we really want to have an extended intro about the advantages of CI in general here?

I think most people arriving here know what Travis and CI is, especially because Travis has been the most used CI provider for R in the last years. Imo the links in the README are enough to get started.

**Comment by pat-s** [comment]
I've extended the "Get-Started" vignette a bit and pretty happy with the current state. 
Let me know if you see the need for more :)
