### ISSUE TITLE
Should we explore a similar appveyor package

### ISSUE THREAD

**Issue by karthik** [ropenscilabs/travis#67]
placeholder

**Comment by krlmlr** [comment]
The name `ci` is available, but the abbreviation "ci" does have another very important meaning in statistics.

**Comment by maelle** [comment]
@krlmlr at the moment, `use_tic()` will create an Appveyor config file for packages, but not activate the Appveyor repo right? Should it at least browse the page?

**Comment by pat-s** [comment]
@maelle {tic} makes use of {travis} and {circle} to do the API work behind the scenes. There is no such package for {appveyor} and I think this should also be discussed outside of this repo, maybe in the ropensci Slack.
If so, the package should offer all possible API endpoint of appveyor, similar to 
{travis} and {circle}.
