### ISSUE TITLE
usethis integration

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#73]
- [ ] Don't import _usethis_
- [ ] Move `use_tic()` and `use_travis_deploy()` to _usethis_
    - Merge to `master`, lifecycle "experimental"
- [ ] Point to _usethis_ for setup
- [ ] Look in _sysreqdb_  for additional dependencies, suggest `addons: apt: ...` entry

**Comment by krlmlr** [comment]
A few functions for setting up GitHub overlap with what's already available in _usethis_. Maybe we should keep importing _usethis_ and suggest _travis_ from _usethis_?

**Comment by pat-s** [comment]
> A few functions for setting up GitHub overlap with what's already available in usethis. Maybe we should keep importing usethis and suggest travis from usethis?

Is this more a "self-note" or a question?

If second, why not outsource this functionality to a well-maintained pkg instead of maintaining redundant code here?

**Comment by pat-s** [comment]
We are now using

- `use_github_token()`
- `edit_file()`
- `proj_get()`
- `browse_travis()` 

from {usethis}. 

I'd say leaving {usethis} in IMPORTS is fine?

Imo `use_travis_deploy()` should live in {travis}.
Feel free to re-open if you want to continue discussing this topic.
