### ISSUE TITLE
Lint travis.yml files

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#74]
Faster than pushing a commit just to see that the `.yml` is malformed.

**Comment by krlmlr** [comment]
@leeper: Would you like to contribute, or point me to your code?

**Comment by leeper** [comment]
My code was here: https://github.com/cloudyr/travisci/blob/master/R/lint.R

In my experience this always gave weird messages because R is not a first class language.

**Comment by krlmlr** [comment]
Thanks. I asked Travis support about linting `language: r` files.
