### ISSUE TITLE
Could use_tic use the current active project instead of current path

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/travis#89]
if there's a current active project?

Most `usethis` functions act on the current project, so it might make sense if `use_tic()` did that too?

**Comment by pat-s** [comment]
Before searching too long: Do you know by chance which helper functions does the path handling in _usethis_?

**Comment by maelle** [comment]
What do you mean? `usethis::proj_get()`?

**Comment by pat-s** [comment]
Yes. Makes sense to use it. What do you think, @krlmlr ?

**Comment by krlmlr** [comment]
Fully agree, we should be more consistent with what _usethis_ is doing.

**Comment by maelle** [comment]
Interested in a PR?

**Comment by pat-s** [comment]
Go ahead!

**Comment by maelle** [comment]
Ok, will do tomorrow!

**Comment by maelle** [comment]
A problem is that it'll mean `usethis` will need to be listed under `Imports`. Is this a deal breaker?

**Comment by maelle** [comment]
`github_repo()` will also need a new default instead of `.`
