### ISSUE TITLE
Could one use use_tic() non interactively?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/travis#90]
Even just for activating normal checks on CI, maybe not deploy keys etc to start with.

What I had tried https://github.com/lockedata/pRojects/issues/74#issuecomment-436684594

**Comment by maelle** [comment]
Well `pRojects`, this way no interactivity would be needed when creating a project. But it is not too bad with interactivity.

**Comment by pat-s** [comment]
All {tic} functionality lives in {tic} now. If the issue still applies, please open a new one :)
