### ISSUE TITLE
Organisation role requirements for use_tic()

### ISSUE THREAD

**Issue by mitchelloharawild** [ropenscilabs/travis#95]
Hi!

I've been trying to set up `tic` for deploying `pkgdown` for `vitae` with @maelle and we ran into an issue with organisation roles. Is it necessary to have admin roles in an organisation for setting tokens in travis or the `vitae` repo?

```r
travis::use_tic()
#> Error: Must have role admin to edit organization ropenscilabs, not member
```

**Comment by pat-s** [comment]
I can only say that I am not sure about this. Maybe org admin rights are not necessary but at least full admin right for the repo as changes to the repo settings need to be made. 

Do you two have these? I do not know how detailed the permission right settings can be in Github even though I am with in a few orgs. But I've never checked in detail.

At last, maybe a person with org admin rights can do it once? Even though I understand that this is tedious.

**Comment by mitchelloharawild** [comment]
For `vitae` I think I have full admin rights to the repo, as I'm able to change all repo settings including deploy keys.

I have manually ran `travis::use_tic()` without checking for organisation admin rights, and was able to add the keys to github without issues. So maybe the test in `github_add_key` can be made less strict?

**Comment by maelle** [comment]
@krlmlr any update? It is quite a hurdle for rOpenSci package authors.

**Comment by krlmlr** [comment]
Can you please try

```r
devtools::install_github("ropenscilabs/travis")
```

? I added a new deploy key to this repo, pretty sure I'm not org admin of ropenscilabs.?

**Comment by maelle** [comment]
@robinlovelace can you try this? Thank you

**Comment by maelle** [comment]
(I am org admin so not a good tester)

**Comment by Robinlovelace** [comment]
Many thanks @krlmlr, looks good to me:

```
travis::use_travis_deploy()
Authenticating with GitHub
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Authenticating with GitHub
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Finished adding deploy keys on GitHub for repo ropensci/stplanr.
Successfully added public deploy key 'travis+tic' to GitHub for ropensci/stplanr. You should receive a confirmation e-mail from GitHub. Delete the key in the repository's settings to revoke access for that key or when you no longer need it.
Authenticating with Travis
Authenticating with GitHub
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Finished updating private environment variable id_rsa for ropensci/stplanr on Travis CI.
Successfully added private deploy key to ropensci/stplanr as secure environment variable id_rsa to Travis CI.
```

**Comment by maelle** [comment]
Yay, thanks @krlmlr for the fix and @Robinlovelace for testing (and asking!), this is a big win!

**Comment by Robinlovelace** [comment]
We should soon find out if it's worked (for some reason the `gh-pages` branch had vanished, making previous build fail): https://travis-ci.org/ropensci/stplanr

**Comment by mpadge** [comment]
Worked for me too - thanks @krlmlr!
